services:
    laravel:
        build: .
        tty: true
        stdin_open: true
        ports:
            - "8000:8000"
            - "5173:5173"
        #entrypoint: ["/bin/sh"]
        #entrypoint: ["/bin/bash", "-l" ,"entrypoint.sh"]
        entrypoint: ["/bin/bash", "-l"]
        #entrypoint: ["/usr/local/bin/php","artisan", "serve","--host", "0"]
        working_dir: /laravel-app
        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        image: bitnami/mysql:8.0.23
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_AUTHENTICATION_PLUGIN: 'mysql_native_password'
        volumes:
            - "./docker/my.cnf:/etc/mysql/my.cnf"
            - 'laravel-mysql-${APP_ENV}:/bitnami/mysql/data'

volumes:
    laravel-mysql-local:
        driver: local
    laravel-mysql-production:
        driver: local